// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: CreateUser.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, name, surname, patronymic)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, name, surname, patronymic
`

type CreateUserParams struct {
	ID         int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	Surname    string
	Patronymic sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Surname,
		arg.Patronymic,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
	)
	return i, err
}
