// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: UpdateUser.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET updated_at = $1, name = $2, surname = $3, patronymic = $4, age = $5, gender = $6, nationality = $7
WHERE id = $8
`

type UpdateUserParams struct {
	UpdatedAt   time.Time
	Name        string
	Surname     string
	Patronymic  sql.NullString
	Age         int32
	Gender      string
	Nationality string
	ID          int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.UpdatedAt,
		arg.Name,
		arg.Surname,
		arg.Patronymic,
		arg.Age,
		arg.Gender,
		arg.Nationality,
		arg.ID,
	)
	return err
}
