// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: UserExistById.sql

package database

import (
	"context"
)

const userExistById = `-- name: UserExistById :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE id = $1
)
`

func (q *Queries) UserExistById(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExistById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
