// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: UserExist.sql

package database

import (
	"context"
	"database/sql"
)

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE name=$1 AND surname=$2 AND patronymic=$3 
)
`

type UserExistsParams struct {
	Name       string
	Surname    string
	Patronymic sql.NullString
}

func (q *Queries) UserExists(ctx context.Context, arg UserExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists, arg.Name, arg.Surname, arg.Patronymic)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
