// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: UserExistByFullName.sql

package database

import (
	"context"
	"database/sql"
)

const userExistByFullName = `-- name: UserExistByFullName :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE name=$1 AND surname=$2 AND patronymic=$3 
)
`

type UserExistByFullNameParams struct {
	Name       string
	Surname    string
	Patronymic sql.NullString
}

func (q *Queries) UserExistByFullName(ctx context.Context, arg UserExistByFullNameParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExistByFullName, arg.Name, arg.Surname, arg.Patronymic)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
