// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Util787/user-manager-api/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateUser(params entities.User) (entities.User, error) {
	ret := _mock.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.User) (entities.User, error)); ok {
		return returnFunc(params)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.User) entities.User); ok {
		r0 = returnFunc(params)
	} else {
		r0 = ret.Get(0).(entities.User)
	}
	if returnFunc, ok := ret.Get(1).(func(entities.User) error); ok {
		r1 = returnFunc(params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - params entities.User
func (_e *MockUserService_Expecter) CreateUser(params interface{}) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", params)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(params entities.User)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.User
		if args[0] != nil {
			arg0 = args[0].(entities.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(user entities.User, err error) *MockUserService_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(params entities.User) (entities.User, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserService
func (_mock *MockUserService) DeleteUser(id int32) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int32) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - id int32
func (_e *MockUserService_Expecter) DeleteUser(id interface{}) *MockUserService_DeleteUser_Call {
	return &MockUserService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", id)}
}

func (_c *MockUserService_DeleteUser_Call) Run(run func(id int32)) *MockUserService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_DeleteUser_Call) Return(err error) *MockUserService_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_DeleteUser_Call) RunAndReturn(run func(id int32) error) *MockUserService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// ExistByFullName provides a mock function for the type MockUserService
func (_mock *MockUserService) ExistByFullName(params entities.FullName) (bool, error) {
	ret := _mock.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for ExistByFullName")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.FullName) (bool, error)); ok {
		return returnFunc(params)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.FullName) bool); ok {
		r0 = returnFunc(params)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(entities.FullName) error); ok {
		r1 = returnFunc(params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_ExistByFullName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistByFullName'
type MockUserService_ExistByFullName_Call struct {
	*mock.Call
}

// ExistByFullName is a helper method to define mock.On call
//   - params entities.FullName
func (_e *MockUserService_Expecter) ExistByFullName(params interface{}) *MockUserService_ExistByFullName_Call {
	return &MockUserService_ExistByFullName_Call{Call: _e.mock.On("ExistByFullName", params)}
}

func (_c *MockUserService_ExistByFullName_Call) Run(run func(params entities.FullName)) *MockUserService_ExistByFullName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.FullName
		if args[0] != nil {
			arg0 = args[0].(entities.FullName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_ExistByFullName_Call) Return(b bool, err error) *MockUserService_ExistByFullName_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserService_ExistByFullName_Call) RunAndReturn(run func(params entities.FullName) (bool, error)) *MockUserService_ExistByFullName_Call {
	_c.Call.Return(run)
	return _c
}

// ExistById provides a mock function for the type MockUserService
func (_mock *MockUserService) ExistById(id int32) (bool, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ExistById")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int32) (bool, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int32) bool); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(int32) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_ExistById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistById'
type MockUserService_ExistById_Call struct {
	*mock.Call
}

// ExistById is a helper method to define mock.On call
//   - id int32
func (_e *MockUserService_Expecter) ExistById(id interface{}) *MockUserService_ExistById_Call {
	return &MockUserService_ExistById_Call{Call: _e.mock.On("ExistById", id)}
}

func (_c *MockUserService_ExistById_Call) Run(run func(id int32)) *MockUserService_ExistById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_ExistById_Call) Return(b bool, err error) *MockUserService_ExistById_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserService_ExistById_Call) RunAndReturn(run func(id int32) (bool, error)) *MockUserService_ExistById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function for the type MockUserService
func (_mock *MockUserService) GetAllUsers(pageSize int, page int, name string, surname string, patronymic string, gender string) ([]entities.User, int, error) {
	ret := _mock.Called(pageSize, page, name, surname, patronymic, gender)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []entities.User
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int, int, string, string, string, string) ([]entities.User, int, error)); ok {
		return returnFunc(pageSize, page, name, surname, patronymic, gender)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int, string, string, string, string) []entities.User); ok {
		r0 = returnFunc(pageSize, page, name, surname, patronymic, gender)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int, string, string, string, string) int); ok {
		r1 = returnFunc(pageSize, page, name, surname, patronymic, gender)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(int, int, string, string, string, string) error); ok {
		r2 = returnFunc(pageSize, page, name, surname, patronymic, gender)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserService_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockUserService_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - pageSize int
//   - page int
//   - name string
//   - surname string
//   - patronymic string
//   - gender string
func (_e *MockUserService_Expecter) GetAllUsers(pageSize interface{}, page interface{}, name interface{}, surname interface{}, patronymic interface{}, gender interface{}) *MockUserService_GetAllUsers_Call {
	return &MockUserService_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", pageSize, page, name, surname, patronymic, gender)}
}

func (_c *MockUserService_GetAllUsers_Call) Run(run func(pageSize int, page int, name string, surname string, patronymic string, gender string)) *MockUserService_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockUserService_GetAllUsers_Call) Return(users []entities.User, totalCount int, err error) *MockUserService_GetAllUsers_Call {
	_c.Call.Return(users, totalCount, err)
	return _c
}

func (_c *MockUserService_GetAllUsers_Call) RunAndReturn(run func(pageSize int, page int, name string, surname string, patronymic string, gender string) ([]entities.User, int, error)) *MockUserService_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserById(id int32) (entities.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int32) (entities.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int32) entities.User); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(entities.User)
	}
	if returnFunc, ok := ret.Get(1).(func(int32) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type MockUserService_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - id int32
func (_e *MockUserService_Expecter) GetUserById(id interface{}) *MockUserService_GetUserById_Call {
	return &MockUserService_GetUserById_Call{Call: _e.mock.On("GetUserById", id)}
}

func (_c *MockUserService_GetUserById_Call) Run(run func(id int32)) *MockUserService_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserById_Call) Return(user entities.User, err error) *MockUserService_GetUserById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_GetUserById_Call) RunAndReturn(run func(id int32) (entities.User, error)) *MockUserService_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) UpdateUser(id int32, params entities.UpdateUserParams) error {
	ret := _mock.Called(id, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int32, entities.UpdateUserParams) error); ok {
		r0 = returnFunc(id, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - id int32
//   - params entities.UpdateUserParams
func (_e *MockUserService_Expecter) UpdateUser(id interface{}, params interface{}) *MockUserService_UpdateUser_Call {
	return &MockUserService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", id, params)}
}

func (_c *MockUserService_UpdateUser_Call) Run(run func(id int32, params entities.UpdateUserParams)) *MockUserService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		var arg1 entities.UpdateUserParams
		if args[1] != nil {
			arg1 = args[1].(entities.UpdateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_UpdateUser_Call) Return(err error) *MockUserService_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_UpdateUser_Call) RunAndReturn(run func(id int32, params entities.UpdateUserParams) error) *MockUserService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRedisService creates a new instance of MockRedisService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisService {
	mock := &MockRedisService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedisService is an autogenerated mock type for the RedisService type
type MockRedisService struct {
	mock.Mock
}

type MockRedisService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisService) EXPECT() *MockRedisService_Expecter {
	return &MockRedisService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRedisService
func (_mock *MockRedisService) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRedisService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedisService_Expecter) Delete(ctx interface{}, key interface{}) *MockRedisService_Delete_Call {
	return &MockRedisService_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockRedisService_Delete_Call) Run(run func(ctx context.Context, key string)) *MockRedisService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedisService_Delete_Call) Return(err error) *MockRedisService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisService_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockRedisService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRedisService
func (_mock *MockRedisService) Get(ctx context.Context, key string, dest any) error {
	ret := _mock.Called(ctx, key, dest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, key, dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRedisService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - dest any
func (_e *MockRedisService_Expecter) Get(ctx interface{}, key interface{}, dest interface{}) *MockRedisService_Get_Call {
	return &MockRedisService_Get_Call{Call: _e.mock.On("Get", ctx, key, dest)}
}

func (_c *MockRedisService_Get_Call) Run(run func(ctx context.Context, key string, dest any)) *MockRedisService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRedisService_Get_Call) Return(err error) *MockRedisService_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisService_Get_Call) RunAndReturn(run func(ctx context.Context, key string, dest any) error) *MockRedisService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockRedisService
func (_mock *MockRedisService) Set(ctx context.Context, key string, value any) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisService_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRedisService_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
func (_e *MockRedisService_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockRedisService_Set_Call {
	return &MockRedisService_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockRedisService_Set_Call) Run(run func(ctx context.Context, key string, value any)) *MockRedisService_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRedisService_Set_Call) Return(err error) *MockRedisService_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisService_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value any) error) *MockRedisService_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInfoRequestService creates a new instance of MockInfoRequestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInfoRequestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInfoRequestService {
	mock := &MockInfoRequestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInfoRequestService is an autogenerated mock type for the InfoRequestService type
type MockInfoRequestService struct {
	mock.Mock
}

type MockInfoRequestService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInfoRequestService) EXPECT() *MockInfoRequestService_Expecter {
	return &MockInfoRequestService_Expecter{mock: &_m.Mock}
}

// RequestAdditionalInfo provides a mock function for the type MockInfoRequestService
func (_mock *MockInfoRequestService) RequestAdditionalInfo(name string) (int, string, string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for RequestAdditionalInfo")
	}

	var r0 int
	var r1 string
	var r2 string
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, string, string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) string); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string) string); ok {
		r2 = returnFunc(name)
	} else {
		r2 = ret.Get(2).(string)
	}
	if returnFunc, ok := ret.Get(3).(func(string) error); ok {
		r3 = returnFunc(name)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockInfoRequestService_RequestAdditionalInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestAdditionalInfo'
type MockInfoRequestService_RequestAdditionalInfo_Call struct {
	*mock.Call
}

// RequestAdditionalInfo is a helper method to define mock.On call
//   - name string
func (_e *MockInfoRequestService_Expecter) RequestAdditionalInfo(name interface{}) *MockInfoRequestService_RequestAdditionalInfo_Call {
	return &MockInfoRequestService_RequestAdditionalInfo_Call{Call: _e.mock.On("RequestAdditionalInfo", name)}
}

func (_c *MockInfoRequestService_RequestAdditionalInfo_Call) Run(run func(name string)) *MockInfoRequestService_RequestAdditionalInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInfoRequestService_RequestAdditionalInfo_Call) Return(age int, gender string, nationality string, err error) *MockInfoRequestService_RequestAdditionalInfo_Call {
	_c.Call.Return(age, gender, nationality, err)
	return _c
}

func (_c *MockInfoRequestService_RequestAdditionalInfo_Call) RunAndReturn(run func(name string) (int, string, string, error)) *MockInfoRequestService_RequestAdditionalInfo_Call {
	_c.Call.Return(run)
	return _c
}
